# -*- coding: utf-8 -*-
"""realtime_fruits

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hq35BNjTIJ49SaO85gEoxiWk57eJFI2k
"""

import cv2
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import time

class_names = ["dragonfruit", "naranjilla", "tamarillo"]

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.resnet18(pretrained=False)
model.fc = nn.Linear(model.fc.in_features, 3)
model.load_state_dict(torch.load("modelo_frutas_resnet18_v3.pth", map_location=device))
model.to(device)
model.eval()

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

cap = cv2.VideoCapture(0)

prev_time = 0

print("Presiona 'q' para salir")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    current_time = time.time()
    fps = 1 / (current_time - prev_time)
    prev_time = current_time

    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_image = Image.fromarray(rgb_frame)
    input_tensor = transform(pil_image).unsqueeze(0).to(device)

    start = time.time()

    with torch.no_grad():
        output = model(input_tensor)
        probs = torch.softmax(output, dim=1)
        _, pred = torch.max(probs, 1)

    end = time.time()
    inference_time = (end - start) * 1000  # ms

    confidence = probs[0][pred.item()].item()

    if confidence < 0.4:
        prediction = "No detectado"
    else:
        prediction = class_names[pred.item()]

    text1 = f"{prediction} ({confidence:.2f})"
    text2 = f"Inference: {inference_time:.1f} ms"
    text3 = f"FPS: {fps:.1f}"

    cv2.putText(frame, text1, (10, 40),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2)

    cv2.putText(frame, text2, (10, 80),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,255,0), 2)

    cv2.putText(frame, text3, (10, 120),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,255), 2)

    cv2.imshow("Clasificacion Tiempo Real", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()